export const API_STATUS_CODES = {
  SUCCESS: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
} as const;

export const MESSAGES = {
  LOGIN_SUCCESS: 'Login successful',
  REGISTER_SUCCESS: 'Registration successful',
  LOGOUT_SUCCESS: 'Logout successful',
  TASK_CREATED: 'Task created successfully',
  TASK_UPDATED: 'Task updated successfully',
  TASK_DELETED: 'Task deleted successfully',
  TASK_NOT_FOUND: 'Task not found',
  TASK_ALREADY_EXISTS: 'Task already exists',
  EMAIL_ALREADY_REGISTERED: 'Email already registered',
  EMAIL_NOT_FOUND: 'Email not found',
  INVALID_CREDENTIALS: 'Invalid credentials',
  INVALID_PASSWORD: 'Invalid password',
  USER_NOT_FOUND: 'User not found',
  USER_ALREADY_EXISTS: 'User already exists',
  USER_CREATED: 'User created successfully',
  USER_UPDATED: 'User updated successfully',
  USER_DELETED: 'User deleted successfully',
  INVALID_TASK_ID: 'Invalid task ID',
  INVALID_TASK_STATUS: 'Invalid task status',
  INVALID_TASK_PRIORITY: 'Invalid task priority',
  INVALID_TASK_SORT_BY: 'Invalid task sort by',
  INVALID_TASK_SORT_ORDER: 'Invalid task sort order',
  INVALID_TASK_DATE_RANGE: 'Invalid task date range',
  INVALID_TOKEN: 'Invalid or expired token',
  VALIDATION_ERROR: 'Validation error',
  INVALID_EMAIL_FORMAT: 'Invalid email format',
  UNAUTHORIZED: 'Unauthorized',
  INTERNAL_SERVER_ERROR: 'Internal server error',
  CATEGORY_CREATED: 'Category created successfully',
  CATEGORY_UPDATED: 'Category updated successfully',
  CATEGORY_DELETED: 'Category deleted successfully',
  CATEGORY_NOT_FOUND: 'Category not found',
  INVALID_CATEGORY_ID: 'Invalid category ID',
  CATEGORY_NAME_REQUIRED: 'Category name is required',
  CATEGORY_NAME_TOO_LONG: 'Category name is too long',
  CATEGORY_ALREADY_EXISTS: 'Category already exists',
} as const;
